# Generated by Django 4.1.2 on 2022-10-19 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_notes', '0002_alter_noteaccesskey_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptednote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='noteaccesskey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
