# Generated by Django 4.1.2 on 2022-10-28 07:20

from django.db import migrations, models
import django.db.models.deletion
import encrypted_notes.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_notes', '0005_encryptednote_uuid_remove_null_noteaccesskey_uuid_remove_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptednote',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='noteaccesskey',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='EncryptedNoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=encrypted_notes.models.EncryptedNoteFile._generate_file_path)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='encrypted_notes.encryptednote')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('note', 'file')},
            },
        ),
    ]
