# Generated by Django 4.1.2 on 2022-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_notes', '0006_alter_encryptednote_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encryptednotefile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='encryptednotefile',
            name='name',
            field=models.CharField(default='test_file.txt', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='encryptednotefile',
            unique_together={('note', 'name')},
        ),
    ]
